version: '3'
services:
  nextjs-app:
    container_name: nextjs-app-2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6905:3000'
    restart: unless-stopped
    command: >
      sh -c "pnpm install && pnpm run dev"
