version: '3'
services:
  nextjs-app:
    container_name: nextjs-app-2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6905:3000'
    restart: unless-stopped
    environment:
      TURBO_FORCE: 'true' # Avoid caching issues
    command: >
      sh -c "pnpm install --frozen-lockfile && pnpm run dev"
